name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      os: ubuntu-latest

  code-quality:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
