name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      os: ubuntu-latest

  coverage:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Run tests with coverage
        run: uv run pytest --cov pyprune
