name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  tests:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Run tests
        run: uv run pytest test
